language: android

jdk:
 - oraclejdk8

env: CI=travis

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  - TERM=dumb

install:
  - ./gradlew assembleDebug

script:
  - ./gradlew checkDebug
  - ./gradlew test

sudo: false
