language: android

jdk:
 - oraclejdk7
 - oraclejdk8

env: CI=travis

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

before_install:
  - TERM=dumb

install:
  - ./gradlew assembleDebug

script:
  - ./gradlew checkDebug
  - ./gradlew test
